# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userroles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='name',
            field=models.CharField(choices=[('watcher', 'watcher'), ('nobody', 'nobody'), ('parent', 'parent'), ('child', 'child')], max_length=100),
        ),
    ]
