# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userroles', '0003_auto_20160704_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='name',
            field=models.CharField(choices=[('nobody', 'nobody'), ('child', 'child'), ('watcher', 'watcher'), ('parent', 'parent')], max_length=100),
        ),
    ]
