# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-17 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userroles', '0004_auto_20160711_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('verbose_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='name',
        ),
        migrations.AddField(
            model_name='userrole',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userroles.Role'),
        ),
    ]
