# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-17 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userroles', '0005_auto_20160718_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='common_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
