# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-17 23:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userroles', '0006_role_common_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='common_name',
        ),
        migrations.AddField(
            model_name='role',
            name='base_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userroles.Role'),
        ),
    ]
